In [3]:
import numpy as np

# Create a one-dimensional array with the first 10 natural numbers
a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Create a 3x3 matrix filled with zeros
a = np.zeros((3, 3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Create a 5x5 matrix filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(5, 5))

print(a)

[[ 9  3  9  9  1]
 [ 2  6 10  7  2]
 [ 6  7  8  7  7]
 [ 5  1  5 10  6]
 [ 3  2 10  8  2]]


In [7]:
# Create a 4x4 matrix filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(4, 4)

print(a)

[[0.87880837 0.08725327 0.25372652 0.14936489]
 [0.1061566  0.20100387 0.51736973 0.8682906 ]
 [0.19863817 0.93986689 0.77671979 0.63280328]
 [0.20826273 0.46173356 0.57318319 0.89590799]]


In [8]:
# Create two one-dimensional arrays of size 5
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

# Perform element-wise operations
addition = a + b
subtraction = a - b
multiplication = a * b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Addition: [ 7  2 19  7  7]
Subtraction: [-5  0  1  1  3]
Multiplication: [ 6  1 90 12 10]


In [9]:
# Create two vectors of size 7
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Find the scalar product
scalar_product = np.dot(a, b)

print(scalar_product)

1400


In [10]:
# Create two matrices of size 2x2 and 2x3
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))

# Multiply the matrices
result = np.dot(a, b)

print(result)

[[24 33 45]
 [31 46 21]]


In [11]:
# Create a 3x3 matrix filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(3, 3))

# Find the inverse of the matrix
inverse = np.linalg.inv(a)

print(inverse)

[[-1.          0.43589744  0.02564103]
 [ 2.         -0.94871795  0.17948718]
 [ 0.          0.12820513 -0.05128205]]


In [12]:
# Create a 4x4 matrix filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(4, 4)

# Transpose the matrix
transposed = np.transpose(a)


print(transposed)

[[0.50420914 0.33352318 0.3310336  0.27242183]
 [0.4453156  0.41943417 0.79883595 0.61277218]
 [0.46972249 0.5238682  0.9880503  0.75308119]
 [0.06380013 0.46766479 0.23867913 0.21048765]]


In [13]:

# Create a 3x4 matrix and a 4-element vector filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)

# Multiply the matrix by the vector
result = np.dot(a, b)

print(result)

[126 118  60]


In [14]:

# Create a 2x3 matrix and a 3-element vector filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(2, 3)
b = np.random.rand(3)

# Multiply the matrix by the vector
result = np.dot(a, b)

print(result)

[0.12298725 0.53290924]


In [15]:

# Create two 2x2 matrices filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

# Perform element-wise multiplication
element_wise_product = a * b

print(element_wise_product)

[[30 21]
 [18 36]]


In [16]:
# Create two 2x2 matrices filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

# Find the product of the matrices
result = np.dot(a, b)


print(result)

[[ 31  92]
 [ 45 100]]


In [17]:
# Create a 5x5 matrix filled with random integers in the range from 1 to 100
a = np.random.randint(1, 101, size=(5, 5))

# Find the sum of the elements
sum_elements = np.sum(a)

print(sum_elements)

1556


In [18]:
# Create two 4x4 matrices filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))

# Find the difference of the matrices
result = a - b


print(result)

[[ 1 -6  4  4]
 [-4 -6  0 -2]
 [ 1 -7  0 -3]
 [-2 -3 -1 -8]]


In [19]:
# Create a 3x3 matrix filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(3, 3)

# Find the vector of row sums
row_sums = np.sum(a, axis=1)

print(row_sums)

[2.2081728  0.9948307  1.83877214]


In [20]:
# Create a 3x4 matrix with arbitrary integers
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Create a matrix with the squares of its elements
squares = a ** 2


print(squares)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [21]:
# Create a 4-element vector with arbitrary integers
a = np.array([16, 25, 36, 49])

# Create a vector with the square roots of its elements
square_roots = np.sqrt(a)


print(square_roots)

[4. 5. 6. 7.]
