In [19]:
import numpy as np

# Create a one-dimensional array with the first 10 natural numbers
a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
# Create a 3x3 matrix filled with zeros
a = np.zeros((3, 3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# Create a 5x5 matrix filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(5, 5))

print(a)

[[ 8  2  2  2  2]
 [ 2  6  4  8  7]
 [ 8  9 10  4  7]
 [ 1 10  6  9  2]
 [10  3  5  7  2]]


In [22]:
# Create a 4x4 matrix filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(4, 4)

print(a)

[[0.24060006 0.89470505 0.27824842 0.06282022]
 [0.49314255 0.41500133 0.49678551 0.95297172]
 [0.70573018 0.56038671 0.93228965 0.60846028]
 [0.04098642 0.5792341  0.36370936 0.6532163 ]]


In [23]:
# Create two one-dimensional arrays of size 5
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

# Perform element-wise operations
addition = a + b
subtraction = a - b
multiplication = a * b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Addition: [ 8 13 14 17 16]
Subtraction: [ 4  1  4  1 -4]
Multiplication: [12 42 45 72 60]


In [24]:
# Create two vectors of size 7
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Find the scalar product
scalar_product = np.dot(a, b)

print(scalar_product)

1400


In [25]:
# Create two matrices of size 2x2 and 2x3
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))

# Multiply the matrices
result = np.dot(a, b)

print(result)

[[78 47 61]
 [74 37 47]]


In [26]:
# Create a 3x3 matrix filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(3, 3))

# Find the inverse of the matrix
inverse = np.linalg.inv(a)

print(inverse)

[[-5.00000000e-01 -3.00000000e+00  1.30000000e+00]
 [ 5.00000000e-01  2.00000000e+00 -9.00000000e-01]
 [ 5.55111512e-17  1.00000000e+00 -2.00000000e-01]]


In [27]:
# Create a 4x4 matrix filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(4, 4)

# Transpose the matrix
transposed = np.transpose(a)


print(transposed)

[[0.80498023 0.18066538 0.30912242 0.25720263]
 [0.31331656 0.62760284 0.75670773 0.93326483]
 [0.54442204 0.66767359 0.90650024 0.34914248]
 [0.98339851 0.1291283  0.49686071 0.92962336]]


In [28]:

# Create a 3x4 matrix and a 4-element vector filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)

# Multiply the matrix by the vector
result = np.dot(a, b)

print(result)

[ 82 118 164]


In [29]:

# Create a 2x3 matrix and a 3-element vector filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(2, 3)
b = np.random.rand(3)

# Multiply the matrix by the vector
result = np.dot(a, b)

print(result)

[0.95269999 0.75323373]


In [30]:

# Create two 2x2 matrices filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

# Perform element-wise multiplication
element_wise_product = a * b

print(element_wise_product)

[[30 14]
 [42  5]]


In [31]:
# Create two 2x2 matrices filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

# Find the product of the matrices
result = np.dot(a, b)


print(result)

[[24 20]
 [27 25]]


In [32]:
# Create a 5x5 matrix filled with random integers in the range from 1 to 100
a = np.random.randint(1, 101, size=(5, 5))

# Find the sum of the elements
sum_elements = np.sum(a)

print(sum_elements)

1501


In [33]:
# Create two 4x4 matrices filled with random integers in the range from 1 to 10
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))

# Find the difference of the matrices
result = a - b


print(result)

[[-2  3 -1 -2]
 [-4  0  0  4]
 [ 5  9  3  7]
 [ 0 -1  2  2]]


In [34]:
# Create a 3x3 matrix filled with random floating-point numbers in the range from 0 to 1
a = np.random.rand(3, 3)

# Find the vector of row sums
row_sums = np.sum(a, axis=1)

print(row_sums)

[1.31724539 1.19574548 1.06757923]


In [35]:
# Create a 3x4 matrix with arbitrary integers
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Create a matrix with the squares of its elements
squares = a ** 2


print(squares)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [36]:
# Create a 4-element vector with arbitrary integers
a = np.array([16, 25, 36, 49])

# Create a vector with the square roots of its elements
square_roots = np.sqrt(a)


print(square_roots)

[4. 5. 6. 7.]
